#+title: Nvim
#+author: Yi Ming

My personal Neovim configuration, which keeps the structure simple and
straightforward by logically distributing the configuration into various
directories. Aims to be highly customizable and have no hacks.

* Table of Contents :toc:
- [[#introduction][Introduction]]
- [[#directory-structure][Directory Structure]]

* Introduction
This configuration doesn't break any of Neovim's default keymaps,
except for =s=, the source-level equivalent of =cl=, which is used as
the [[https://github.com/easymotion/vim-easymotion#default-bindings][easymotion-prefix]](In fact the functionality of easymotion is
provided by a plugin called [[https://github.com/phaazon/hop.nvim][hop.nvim]]). Also, =<BS>= is mapped to =:noh=
in normal mode.

Except for the entry file init.vim, all configuration is done by Lua.
The reason to use init.vim instead of init.lua is to maintain support
for classic Vim or Vim emulators such as IdeaVim, VSCodeVim, or FakeVim
that partially support VimScript.

* Directory Structure
#+begin_src screen
├── lua
│   ├── core
│   │   ├── lspconfig.lua
│   │   ├── treesitter.lua
│   │   └── ...
│   ├── debug
│   │   ├── dap.lua
│   │   ├── dap-ui.lua
│   │   └── ...
│   ├── edit
│   │   ├── cmp.lua
│   │   ├── copilot.lua
│   │   └── ...
│   ├── efficiency
│   │   ├── session-manager.lua
│   │   ├── telescope.lua
│   │   └── ...
│   ├── interface
│   │   ├── bufferline.lua
│   │   ├── lualine.lua
│   │   └── ...
│   ├── language
│   │   ├── jdtls.lua
│   │   └── tex.lua
│   ├── tool
│   │   ├── gitsigns.lua
│   │   ├── tree.lua
│   │   └── ...
│   ├── keymaps.lua
│   ├── plugins.lua
│   └── init.lua
├── .gitignore
├── stylua.toml
├── LICENSE
├── README.org
├── ginit.vim
└── init.vim
#+end_src
