return {
  "monaqa/dial.nvim",
  keys = {
    {
      "<C-a>",
      function()
        require("dial.map").inc_normal()()
      end,
    },
    {
      "<C-x>",
      function()
        require("dial.map").dec_normal()()
      end,
    },
    {
      "<C-a>",
      function()
        require("dial.map").inc_visual()()
      end,
    },
    {
      "<C-x>",
      function()
        require("dial.map").dec_visual()()
      end,
    },
    {
      "g<C-a>",
      function()
        require("dial.map").inc_gvisual()()
      end,
    },
    {
      "g<C-x>",
      function()
        require("dial.map").dec_gvisual()()
      end,
    },
  },
}
