-- Keybindings are only used for lazy loaded plugins
vim.keymap.set("n", "<leader>db", "<Cmd>DBUIToggle<CR>")
vim.keymap.set("n", "<leader>lo", "<Cmd>SymbolsOutline<CR>")
vim.keymap.set("n", "<leader>a", "<Cmd>AerialToggle<CR>")
vim.keymap.set("n", "<leader>tb", "<Cmd>TroubleToggle<CR>")
vim.keymap.set("n", "<leader>zm", "<Cmd>ZenMode<CR>")
vim.keymap.set("n", "<leader>tw", "<Cmd>Twilight<CR>")
vim.keymap.set("n", "<leader>ng", "<Cmd>Neogit<CR>")
vim.keymap.set("n", "<leader>dvo", "<Cmd>DiffviewOpen<CR>")
vim.keymap.set("n", "<leader>dvh", "<Cmd>DiffviewFileHistory<CR>")
vim.keymap.set("n", "<leader>dvc", "<Cmd>DiffviewClose<CR>")
