-- Keybindings are only used for lazy loaded plugins
vim.keymap.set("n", "<leader>db", "<Cmd>DBUIToggle<CR>", { desc = "Toggle UI" })
vim.keymap.set("n", "<leader>lo", "<Cmd>SymbolsOutline<CR>")
vim.keymap.set("n", "<leader>a", "<Cmd>AerialToggle<CR>")
vim.keymap.set("n", "<leader>tz", "<Cmd>ZenMode<CR>", { desc = "Zen Mode" })
vim.keymap.set("n", "<leader>tt", "<Cmd>Twilight<CR>", { desc = "Twilight" })
vim.keymap.set("n", "<leader>ng", "<Cmd>Neogit<CR>")
vim.keymap.set("n", "<leader>dvo", "<Cmd>DiffviewOpen<CR>")
vim.keymap.set("n", "<leader>dvh", "<Cmd>DiffviewFileHistory<CR>")
vim.keymap.set("n", "<leader>dvc", "<Cmd>DiffviewClose<CR>")
