-- Keybindings are only used for lazy loaded plugins
vim.keymap.set("n", "<leader>db", ":DBUIToggle<CR>")
vim.keymap.set("n", "<leader>lo", ":SymbolsOutline<CR>")
vim.keymap.set("n", "<leader>a", ":AerialToggle<CR>")
vim.keymap.set("n", "<leader>tb", ":TroubleToggle<CR>")
vim.keymap.set("n", "<leader>zm", ":ZenMode<CR>")
vim.keymap.set("n", "<leader>tw", ":Twilight<CR>")
vim.keymap.set("n", "<leader>ng", ":Neogit<CR>")
vim.keymap.set("n", "<leader>dvo", ":DiffviewOpen<CR>")
vim.keymap.set("n", "<leader>dvf", ":DiffviewFileHistory<CR>")
vim.keymap.set("n", "<leader>dvc", ":DiffviewClose<CR>")
